config/routes.rb
Swimdb::Application.routes.draw do

  match 'auth/:provider/callback' => "users/authentications#create"
  namespace :adminarea do
    resources :users
  end
  devise_for :admins

  get 'admins/edit' => 'admins/registrations#edit', :as => 'edit_admin_registration'
  put 'admins' => 'admins/registrations#update', :as => 'admin_registration'

  devise_for :users, :controllers => {:registrations => 'users/registrations'}# :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :users do
    resources :authentications
  end

  resources :schedules do
    resources :comments
  end
  root :to => "schedules#index"

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  embedded_in :schedule, :inverse_of => :comments
  referenced_in :user

  field :body
  field :created_at, :type => Time
  field :cached_user
  validates_presence_of :user, :body

  after_validation :cache_user
  after_validation :set_created_at


  private
  def set_created_at
    self.created_at = Time.now
    true
  end

  def cache_user
    unless self.user == nil
      self.cached_user = self.user.username
    end
    true
  end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  include AuthUserAdmin
  belongs_to :schedule
  actions :create, :destroy
  before_filter :auth_user_admin!
  #before_filter :authenticate_user!

  def create
    @schedule = Schedule.find(params[:schedule_id])
    @comment = @schedule.comments.build(params[:comment])
    @comment.user = current_user

    create! do |success, failure|
      success.html { redirect_to parent_url}
      success.js
      failure.html { redirect_to parent_url }
      failure.js  { head :unprocessable_entity }
    end
    #respond_to do |format|
    #  if @comment.save
    #    flash[:notice] = 'Comment was successfully created.'
    #    format.html { redirect_to schedule_path(@schedule) }
    #    format.js
    #  else
    #    @schedule
    #  end
    #end
  end


  def destroy
#<<<<<<< HEAD
#    @schedule = Schedule.find(params[:schedule_id])
#    @comment = @schedule.comments.find(params[:id])
#
#    @schedule.comments.delete_if{|comment| comment.id == @comment.id}
#    if @schedule.save
#      Schedule.decrement(@schedule.id, :comments_count => 1)
#      flash[:notice] = "Successfully destroyed comment."
#    else
#      flash[:error] = "dag, yo."
#    end
#    redirect_to @schedule
#=======
    destroy!{ parent_url }
  end
end

app/views/comments/_comment.html.haml
%li.comment
  %strong
    = comment.cached_user
  %em.date
    = comment.created_at
  %br
  %p.content
    =comment.body
  - if (user_signed_in? && comment.user == current_user) || admin_signed_in?
    %ul.controls
      %li= link_to "Destroy", schedule_comment_path(@schedule, comment), :method => :delete, :confirm => "Are you sure?"

app/views/comments/_form.html.haml
= form_for [@schedule, @schedule.comments.build], :remote =>true do |f|
  %ul.formList
    %li
      = f.label :body, "Comment"
      = f.text_area :body
    %li
      = f.submit "Post Comment"

app/views/comments/create.js.haml
!= "$('#comments_count').html('<h2>#{pluralize(@schedule.comments.size,'comment')}</h2>');"
!= "$('#comments').append('#{escape_javascript(render(:partial => @comment))}');"
!= "$('#new_comment')[0].reset();"

app/views/comments/new.html.haml
-title "Comment"

= render 'form'

%ul.controls
  %li= link_to 'Back', @schedule