config/routes.rb
Swimdb::Application.routes.draw do

  match 'auth/:provider/callback' => "users/authentications#create"
  namespace :adminarea do
    resources :users
  end
  devise_for :admins

  get 'admins/edit' => 'admins/registrations#edit', :as => 'edit_admin_registration'
  put 'admins' => 'admins/registrations#update', :as => 'admin_registration'

  devise_for :users, :controllers => {:registrations => 'users/registrations'}# :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :users do
    resources :authentications
  end

  resources :schedules do
    resources :comments
  end
  root :to => "schedules#index"

end

app/models/schedule.rb
class Schedule
  include Mongoid::Document
  include Mongoid::Timestamps

  referenced_in :user
  field :title
  field :description
  field :original_date, :type => Date

  field :tags, :type => Array
  embeds_many :items
  accepts_nested_attributes_for :items

  embeds_many :comments
  #cache
  field :cached_user

  before_save :cache_user
  validates_presence_of :title, :description
  validates_presence_of :taggings, :if => Proc.new{ self.tags == nil}

  validates_associated :items
  validates_associated :comments, :allow_nil => true

  validate :itemscount

  def self.by_tag(tag)
    where(:tags => /#{tag}/i)
  end

  #virtual attributes
  def taggings=(value)
    unless value.nil?
      self.tags = value.scan(/\w+|,|\./).delete_if{|t| t =~ /,|\./}
    end
  end
  def taggings
    tags.join(" ") if tags
  end

  def date
    if original_date == nil
      created_at.to_date if created_at
    else
      original_date
    end
  end
  def date=(value)
    self.original_date = value if value
  end

  def full_schedule_distance
    distance = 0
    last_outer = 1
    last_inner = 1
    for item in items
      if item.info
        next
      end
      case item.level
        when 0
          distance += item.full_distance
          last_outer = 1
          last_inner = 1
        when 1
          distance += item.full_distance * last_outer
          last_inner = 1
        when 2
          distance += item.full_distance * last_outer * last_inner
      end
      last_outer = item.outer unless (item.outer == nil)
      last_inner = item.inner unless (item.inner == nil)
    end
    return distance
  end

  private

  def cache_user
    unless self.user == nil
      self.cached_user = self.user.username
    end
  end

  def itemscount
    errors.add :items, "There has to be at least 1 Item" if self.items.empty?
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < InheritedResources::Base
  include AuthUserAdmin
  before_filter :auth_user_admin!, :except => [:show, :index]
  has_scope :by_tag

  def show
    @schedule = Schedule.find(params[:id])
  end

  def index
    @schedules = apply_scopes(Schedule).paginate(:per_page => 20, :page => params[:page])
    unless @schedules.count == 0
      @tags = SchedulesHelper::TagCloud.build.find()
      render :layout => 'with_tagcloud'
    end
  end

  def create
    #remove the empty item
    params[:schedule][:items].delete_if{|i| i[:text] == ""}
    @schedule = Schedule.new(params[:schedule])
    @schedule.user = current_user
    create!
  end

  #def update
  #  params[:schedule][:items].delete_if{|i| i[:text] == ""}
  #  @schedule = Schedule.find(params[:id])
  #  if @schedule.update_attributes(params[:schedule])
  #    flash[:notice] = "Successfully updated genre."
  #    redirect_to @schedule
  #  else
  #    render :action => 'edit'
  #  end
  #end



  def update
    items = params[:schedule][:items].delete_if{|i| i[:text] == ""}

    i = []
    errors = false
    items.each do |item|
      i.push(Item.new(item))
      unless i.last.valid?
        errors = true
      end
    end
    @schedule = Schedule.find(params[:id])

    if errors
      @schedule.items = i
      @schedule.valid?
      render :action => 'edit'
      return
    else
      #now i know that all items are valid
      if @schedule.items.count >= items.count
        #more items in the schedule than in the hash => delete them
        @schedule.items.each_with_index do |item, index|
          if index > items.count-1
            @schedule.items[index].delete
          else
            @schedule.items[index].update_attributes(items[index])
          end
        end
      else
        #more items in the hash => create new items
        items.each_with_index do |item, index|
          if index > @schedule.items.count-1
            #create new items
            @schedule.items.build(item)
          else
            @schedule.items[index].update_attributes(item)
          end
        end
        @schedule.save
      end
      params[:schedule].delete("items")

      update!
    end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  # map_reduce für die Tags aller Schedules
  class TagCloud
    def self.map
      <<-MAP
      function(){
        this.tags.forEach(function(tag){
          emit(tag, 1);
        });
      }
      MAP
    end

    def self.reduce
      <<-REDUCE
      function(prev, current) {
        var count = 0;
        for (index in current) {
            count += current[index];
        }
        return count;
      }
      REDUCE
    end

    def self.build
      Schedule.collection.map_reduce(map, reduce, :query => {})
    end
  end

end

app/views/schedules/_comments_area.html.haml
#comments_area
  #comments_count
    - unless @schedule.comments.empty?
      %h2= pluralize(@schedule.comments.count, 'Comment')
  %ul#comments
    = render :partial => @schedule.comments.sort_by(&:created_at)
  %br
  - if user_signed_in?
    = render :partial => "/comments/form"

app/views/schedules/_form.html.haml
- stylesheet 'jqueryui/jquery-ui-1.8.5.custom'
- javascript 'jquery/jquery-ui-1.8.6.datepicker.min'

= form_for @schedule do |f|
  = f.error_messages
  %ul.formlist
    %li#name
      .label= f.label :title
      .field= f.text_field :title, :id => 'name'
    %li#items
      - @schedule.items.each do |item|
        = f.fields_for item do |ff|
          = render :partial => 'item', :locals => {:f => ff}
      %p= add_child_link "(add item)", :items
      = new_child_fields_template(f, :items)
    %li#description
      .label= f.label :description
      .field= f.text_area :description, :rows => 7, :cols => 60, :id => 'description'

    %li#name
      .label= f.label :date, "Original Date"
      .field
        = f.text_field :date
        ="Today if empty"
    %li#tags
      .label= f.label :taggings
      .field= f.text_field :taggings, :id => 'taggings'
    %li.actions
      = f.submit 'Save'

app/views/schedules/_item.html.haml
%fieldset.item
  %ul.horizontal
    %li= f.text_field :text,                             :id => 'text',  :class => 'item-text',  :size => 40, :name => 'schedule[items][][text]'
    -#%li= f.number_field :level, :in => 0..2, :step => 1, :id => 'level', :class => 'item-level', :size => 10, :name => 'schedule[items][][level]'
    %li= f.select :level, %w[0 1 2], {}, {:id => 'level', :class => 'item-level', :name => 'schedule[items][][level]'}
    %li= remove_child_link "(remove)", f

app/views/schedules/_item_fields.html.haml
%li
  = f.number_field :level, :in => 0..2, :step => 1, :class => 'item-level'
  = f.text_field :text, :class => 'item-text'
  = f.link_to_remove "Remove this item"
    %li
      %ul#item_fields
        -#@schedule.items.each_with_index do |item, n|
        = f.fields_for :items do |builder|
          %li
            = builder.number_field :level, :in => 0..2, :step => 1, :class => 'item-level'
            = builder.text_field :text, :class => 'item-text'
            = builder.number_field :rank, :in => 0..20, :step => 1, :class => 'item-rank'
            -# unless builder.object.new_record?
              = builder.link_to_remove "Remove this item"
        =# f.link_to_add "Add a item", :items

app/views/schedules/edit.html.haml
-title "Edit Schedule"

= render 'form'

%ul.controls
  %li= link_to "Back", @schedule
  %li= link_to "Show All", schedules_path

app/views/schedules/index.html.haml
-title "Schedules"
%ul
  = will_paginate @schedules
  - for schedule in @schedules
    %li
      %strong
        =link_to schedule.title, schedule
      .date
        =schedule.date.strftime('%d. %b, %Y') #format noch falsch gleich über i18 richtig machen
      .count
        =pluralize(schedule.comments.count, 'Comment')

  - if user_signed_in?
    %li
      = link_to 'New Schedule', new_schedule_path

app/views/schedules/new.html.haml
-title "Schedules"

= render 'form'

%ul.controls
  %li= link_to 'Back', schedules_path

app/views/schedules/show.html.haml
- title @schedule.title
#schedule
  %strong.user
    =@schedule.cached_user
  %div
    %em.date
      =@schedule.date.strftime('%d. %b, %Y')
  .tags
    =@schedule.taggings
  %p.description
    =@schedule.description
  %ul.items
    -for item in @schedule.items
      %li{:class => [!item.info? && ["textitem", "textlvl#{item.level}"], item.info? && ["infoitem", "infolvl#{item.level}"]]}
        - if item.info
          = item.info
        - else
          = item.text
    %li.distance
      Volle Distanz:
      =@schedule.full_schedule_distance
      m
  %ul.controls
    - if (user_signed_in? && @schedule.user == current_user) || admin_signed_in?
      %li= link_to "Edit", edit_schedule_path(@schedule)
      %li= link_to "Destroy", @schedule, :confirm => 'Are you sure?', :method => :delete
    %li= link_to "Show All", schedules_path
= render :partial => 'comments_area'