config/routes.rb
Swimdb::Application.routes.draw do

  match 'auth/:provider/callback' => "users/authentications#create"
  namespace :adminarea do
    resources :users
  end
  devise_for :admins

  get 'admins/edit' => 'admins/registrations#edit', :as => 'edit_admin_registration'
  put 'admins' => 'admins/registrations#update', :as => 'admin_registration'

  devise_for :users, :controllers => {:registrations => 'users/registrations'}# :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :users do
    resources :authentications
  end

  resources :schedules do
    resources :comments
  end
  root :to => "schedules#index"

end

app/views/shared/_head.html.haml
%title
  = "- SwimDB - | " << (yield(:title) || "Untitled")
%meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
= yield(:more_stylesheets)
-# compass stylesheets
= stylesheet_link_tag 'compiled/screen', :media => 'screen, projection'
= stylesheet_link_tag 'compiled/print', :media => 'print'
/[if lt IE 8]
  = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
= javascript_include_tag 'jquery/jquery-1.4.4.min', 'jquery/rails'
= yield(:more_javascript)
= javascript_include_tag "application"

= csrf_meta_tag
= yield(:head)

app/views/shared/_tag_cloud.html.haml
#tag_cloud
  %h3
    TagCloud:
  - tag_cloud(@tags, %w(tag_size_1 tag_size_2 tag_size_3 tag_size_4 tag_size_5 tag_size_6)) do |tag, css_class|
    = link_to tag, params.merge(:by_tag => tag), :class => css_class
  %p= link_to "Show all", schedules_path

app/views/shared/_user_nav.html.haml
#user_nav
  %ul
    #logo
      logo
    %li.first= link_to "Home", root_url
    - if user_signed_in?
      %li
        = "Hello #{current_user.username}. Not you?"
        = link_to "Logout", destroy_user_session_path
      %li
        = link_to "Edit Profile", edit_users_authentication_path(current_user)
    - elsif admin_signed_in?
      #admin_nav
        %li
          = link_to "Admin Area", adminarea_users_path
        %li
          = "Admin access as #{current_admin.email}"
          = link_to "Logout Admin", destroy_admin_session_path
        %li
          = link_to "Edit Admin Profile", edit_admin_registration_path
    - else
      %li
        = link_to "Login or SignUp", users_authentications_path
    %li.last About